import { users } from "@trader/db";
import { TRPCError } from "@trpc/server";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { createContext, type AppUser, type Context } from "../src/context";
import { appRouter } from "../src/routers/_app";
import { adminProcedure, createCallerFactory, router } from "../src/trpc";
import { API_TEST_COMPANY, clearTestUsers, pool, seedCompany, testDb } from "./helpers";

/**
 * Callers run the real middleware chain, so these assert the gates as deployed
 * rather than the handler bodies in isolation.
 */
const createCaller = createCallerFactory(appRouter);

/** A throwaway router purely to prove the admin gate rejects a worker. */
const adminOnlyRouter = router({
  secret: adminProcedure.query(() => "ok"),
});
const createAdminCaller = createCallerFactory(adminOnlyRouter);

beforeAll(seedCompany);
beforeEach(clearTestUsers);
afterAll(async () => {
  await clearTestUsers();
  await pool.end();
});

async function contextFor(clerkUserId: string): Promise<Context> {
  return createContext({ auth: { clerkUserId }, db: testDb });
}

/**
 * Inserts through Drizzle rather than raw SQL: `id` is a UUIDv7 generated by
 * `$defaultFn` in the schema, not a database default, so a raw INSERT would hit
 * a not-null violation. Fixtures should use the same path the application does.
 */
async function makeUser(clerkUserId: string, role: AppUser["role"], active = true) {
  await testDb.insert(users).values({
    companyId: API_TEST_COMPANY,
    clerkUserId,
    role,
    name: `Test ${role}`,
    active,
  });
}

describe("me.get", () => {
  it("rejects an unauthenticated caller", async () => {
    const ctx = await createContext({ auth: null, db: testDb });
    const caller = createCaller(ctx);

    await expect(caller.me.get()).rejects.toThrow(TRPCError);
    await expect(caller.me.get()).rejects.toMatchObject({ code: "UNAUTHORIZED" });
  });

  it("returns the caller's own role", async () => {
    await makeUser("api_test_foreman", "foreman");
    const caller = createCaller(await contextFor("api_test_foreman"));

    const me = await caller.me.get();
    expect(me.role).toBe("foreman");
    expect(me.companyId).toBe(API_TEST_COMPANY);
  });

  it("rejects a deactivated account", async () => {
    // Deletion is defined as deactivate-and-anonymise, because labor history
    // survives by trigger and by retention law. An account that could still
    // clock in after "deletion" would make that definition cosmetic.
    await makeUser("api_test_gone", "worker", false);
    const caller = createCaller(await contextFor("api_test_gone"));

    await expect(caller.me.get()).rejects.toMatchObject({ code: "UNAUTHORIZED" });
  });

  it("does not expose pay rate", async () => {
    // SPEC §5: a worker cannot see pay. Reading one's own record must not become
    // the seam through which that leaks once pay rates are populated.
    await makeUser("api_test_pay", "worker");
    const caller = createCaller(await contextFor("api_test_pay"));

    const me = await caller.me.get();
    expect(me).not.toHaveProperty("payRateCents");
  });
});

describe("role gates", () => {
  it("rejects a worker from an admin procedure", async () => {
    await makeUser("api_test_worker", "worker");
    const caller = createAdminCaller(await contextFor("api_test_worker"));

    await expect(caller.secret()).rejects.toMatchObject({ code: "FORBIDDEN" });
  });

  it("admits an admin", async () => {
    await makeUser("api_test_boss", "admin");
    const caller = createAdminCaller(await contextFor("api_test_boss"));

    await expect(caller.secret()).resolves.toBe("ok");
  });
});
